[project]
name = "auto-email"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-auth-httplib2>=0.2.0",
    "gspread>=6.2.1",
    "oauth2client>=4.1.3",
    "pandas>=2.3.1",
]
